name: Post code style suggestion as GitHub comments
inputs:
  format_paths:
    descriptions: 'Paths formatted by JuliaFormatter'
    required: true
    default: '"."'
  
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
      - name: Install dependencies
        run: |
          using Pkg
          Pkg.add([
              PackageSpec("JuliaFormatter"),
              PackageSpec(url = "https://github.com/tkf/JuliaProjectFormatter.jl.git"),
          ])
        shell: julia --color=yes {0}

      - name: Format Julia files
        run: |
          using JuliaFormatter
          format(${{ inputs.format_paths }})
        shell: julia --color=yes --compile=min -O0 {0}
      - name: suggester / JuliaFormatter
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaFormatter
          fail_on_error: true

      # reviewdog/action-suggester not using `cleanup` flag?
      - name: Cleanup
        if: success() || failure()
        run: |
          git checkout -- .
          git clean --force
        shell: bash

      - name: Format Julia project files
        if: success() || failure()
        run: |
          using JuliaProjectFormatter
          format_projects()
        shell: julia --color=yes --compile=min -O0 {0}
      - name: suggester / JuliaProjectFormatter
        if: success() || failure()
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaProjectFormatter
          fail_on_error: true
